### ISSUE TITLE
REVISED Checklist of Reqs

### ISSUE THREAD

**Issue by ebeshero** [ebeshero/digitalStorytelling#2]
Assignments

- [x] Blog (25%)
We’ll begin by establishing and maintaining a web presence. You’ll create a blog and link supporting social media (Facebook, Twitter, YouTube) to it. Your blog will focus on – and showcase – your development as a digital storyteller. You’ll use your blog to turn in class projects, respond to assignments, experiment with new techniques, interact with your classmates and professors, and more. You’ll be required to keep your blog active by making at least one unique post and linking to one new blog or other kind of site each week. Your blog should help you develop a keen sense of voice, audience, and purpose.

- [x]  Image + Design Projects/2 (5%)
- [x] (Second?)
You will create two small image + design projects of your choice. You can choose from the following list: a meme (or sequence of memes equivalent to two projects); an animated GIF; an infographic; a digital poster or collage; a visual timeline or other visual/digital element that can be used to illustrate or complement a traditional narrative.

- [ ] ONE Photo Essay/Travelogue (15%). (Was 2, for 20%) 
You will learn how digital images and technologies interact with traditional narrative writing by producing two photo essay/travelogues. The balance between images/digitized content and written narrative should be 50/50 and the text and digital elements should work together to tell a story that couldn’t be told using simply one or the other technique.

- [ ] Audio + Sound Project/ 2 (30%) (Was 1, for 25%)
_ [ ] Second, different in texture/composition elements from the first
Make two of these. Options:
 A podcast/radio essay.
You’ll record, edit and produce a 15-minute podcast that will include a scripted narrative, an interview/conversation, and music or sound effects. OR
A sound essay.
You’ll use found sounds as a way to tell or interweave with narrative. You can, for example, record the sounds of a busy diner while interviewing a waitress about her work. Or you can record a poet reading a poem, then intersperse sound elements that enhance the experience for the listener.

- [ ] Short Video Story/1 (25%)
You’ll script, shoot, and edit your own short (under 3 minutes) narrative film. Your film could be a book trailer, an animated short, a sequence of edited found images that you weave together into unique content, a visual memoir/essay, a video poem or short story, etc.

**Comment by ebeshero** [comment]
@PPH3 After reviewing your blog, I decided maybe we should revise the requirements a bit so you can keep building the sound elements/sound compositions, which seems a real strength and interest thus far! Compare the above checklist against our original specs and let me know if you agree. 

So far I think you're keeping up w at least one blog post per week, though you might be linking out to other sites more. The sound features of your music are superb! I'd like you to write at least one more post involving sound in an intensive/creative way, perhaps a different way than you've tried so far. One thought might be to play a piece with all the parts, then unpack the bass line in a separate thread (perhaps other parts too?) and discuss how you produce a musical composition part by part...what do you think?

I've checked off the requirements I think you've completed so far...let me know if you think I missed anything. And it's really impressive work, by the way...I hope you'll maintain it!

**Comment by ebeshero** [comment]
Note: you're incorporating images well, but I don't see any that are, well, indispensable to telling the narrative...so that is why I haven't marked the photo essay complete yet. I am open, though, to considering multimedia of any kind placed in necessary counterpoint with conventional paragraphs.

**Comment by PPH3** [comment]
Just posted a piece that features a voice recording explaining the nuts and bolts behind one of our songs. There is another voice recording on the Minor Details post. I hope these meet the requirements for the vocal stuff. Tomorrow, I will work on the photo essay, then on to the video story.

**Comment by ebeshero** [comment]
@PPH3 I've written my colleagues to help with the final evaluation, now that you've completed work!
